### ISSUE TITLE
Calls to numpy.random.rand fail on GPU

### ISSUE THREAD

**Issue by adarshyoga** [IntelPython/numba-dppy#102]
Rambo workload has calls to "numpy.random.rand" to initialize a set of vectors with random numbers. Parallelization of these calls on GPU will speedup the execution.

    for i in range(nevts):
        for j in range(nout):
            C1[i, j] = numpy.random.rand()
            F1[i, j] = numpy.random.rand()
            Q1[i, j] = numpy.random.rand()*numpy.random.rand()

**Comment by diptorupd** [comment]
@adarshyoga you please test #141 to see if that addresses this issue.

**Comment by diptorupd** [comment]
@adarshyoga I am closing the issue as it has been fixed for a while. Please reopen if you see a regression.
