### ISSUE TITLE
UMAP fails due to unsupported argsort function

### ISSUE THREAD

**Issue by adarshyoga** [IntelPython/numba-dppy#108]
The following kernel in UMAP fails with an unsupported feature error. Likely due to the presence of argsort function in prange kernel. 
   
 for row in numba.prange(X.shape[0]):
        # v = np.argsort(X[row])  # Need to call argsort this way for numba
        v = X[row].argsort(kind="quicksort")
        v = v[:n_neighbors]
        knn_indices[row] = v

**Comment by diptorupd** [comment]
`Argsort` support has been added using a `dpnp` library call. @adarshyoga Please verify and reopen if you still see the issue.
