### ISSUE TITLE
Numba-dppy examples need to be updated to use dpctl.memory instead of dpctl._memory

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/numba-dppy#137]
The https://github.com/IntelPython/numba-dppy/blob/main/numba_dppy/examples/pairwise_distance.py example still uses the `dpctl._memory` module instead of the new `dpctl.memory` module. The same issue may be present in other examples as well.

**Comment by vlad-perevezentsev** [comment]
@diptorupd This issue duplicates the https://github.com/IntelPython/numba-dppy/issues/132 .
PR already exists to this issue. https://github.com/IntelPython/numba-dppy/pull/136

**Comment by vlad-perevezentsev** [comment]
Duplicated.
