### ISSUE TITLE
Gaps in supported Atomics Operation

### ISSUE THREAD

**Issue by 1e-to** [IntelPython/numba-dppy#156]
Evaluate if Supported Atomics Operation are currently supported for numba-dppy.

class add(ary, idx, val)
Perform atomic ary[idx] += val. Returns the old value at the index location as if it is loaded atomically.

| type | CUDA | DPPY |
| --- | --- | ---|
| int32 | + | + |
| int64 | - | + |
| float32 | + | + |
| float64 | + | + |

class sub(ary, idx, val)

| type | CUDA | DPPY |
| --- | --- | ---|
| int32 | + | + |
| int64 | - | + |
| float32 | + | + |
| float64 | + | + |

class compare_and_swap(ary, old, val)
Conditionally assign val to the first element of an 1D array ary if the current value matches old.
Returns the current value as if it is loaded atomically.

| type | CUDA | DPPY |
| --- | --- | ---|
| all? (not defined in guide) | + | - |

class max(ary, idx, val)
Perform atomic ary[idx] = max(ary[idx], val).
Returns the old value at the index location as if it is loaded atomically.

| type | CUDA | DPPY |
| --- | --- | ---|
| int32 | + | - |
| int64 | + | - |
| float32 | + | - |
| float64 | + | - |
| uint32 | + | - |
| uint64 | + | - |

class min(ary, idx, val)
Perform atomic ary[idx] = min(ary[idx], val).
Returns the old value at the index location as if it is loaded atomically.

| type | CUDA | DPPY |
| --- | --- | ---|
| int32 | + | - |
| int64 | + | - |
| float32 | + | - |
| float64 | + | - |
| uint32 | + | - |
| uint64 | + | - |

class nanmax(ary, idx, val)
Perform atomic ary[idx] = max(ary[idx], val).
NOTE: NaN is treated as a missing value such that: nanmax(NaN, n) == n, nanmax(n, NaN) == n
Returns the old value at the index location as if it is loaded atomically.

| type | CUDA | DPPY |
| --- | --- | ---|
| int32 | + | - |
| int64 | + | - |
| float32 | + | - |
| float64 | + | - |
| uint32 | + | - |
| uint64 | + | - |

class nanmin(ary, idx, val)
Perform atomic ary[idx] = min(ary[idx], val).
NOTE: NaN is treated as a missing value, such that: nanmin(NaN, n) == n, nanmin(n, NaN) == n
Returns the old value at the index location as if it is loaded atomically.

| type | CUDA | DPPY |
| --- | --- | ---|
| int32 | + | - |
| int64 | + | - |
| float32 | + | - |
| float64 | + | - |
| uint32 | + | - |
| uint64 | + | - |

**Comment by PokhodenkoSA** [comment]
Related:
- https://github.com/IntelPython/numba-dppy/issues/86
- https://github.com/IntelPython/numba/pull/2

**Comment by 1e-to** [comment]
https://github.com/IntelPython/numba-dppy/issues/161

**Comment by 1e-to** [comment]
https://github.com/IntelPython/numba-dppy/pull/184
