### ISSUE TITLE
Implement SYCL local memory

### ISSUE THREAD

**Issue by 1e-to** [IntelPython/numba-dppy#164]
We need an analog to implement the behavior numba.cuda.shared.array

- Possibly we need data structure for local memory.
- `dppy.local.static_alloc(shape=10, dtype=float32)` should looks like array creation `dppy.local.array(shape=10, dtype=float32)`
- `dtype` should be Numba or NumPy type? Try to change to NumPy types.

**Comment by reazulhoque** [comment]
This issue is resolved. Example of local memory creation in test [here](https://github.com/IntelPython/numba-dppy/blob/0.14.3/numba_dppy/tests/kernel_tests/test_barrier.py#L87).
