### ISSUE TITLE
Enable debug option inside dppy.kernel 

### ISSUE THREAD

**Issue by akharche** [IntelPython/numba-dppy#174]
Now debug information for kernels is emitted only if `NUMBA_DPPY_DEBUG` environment is set.  
Add ability to enable debugging via decorator like in Numba.cuda `@cuda.jit(debug=True)`.

**Comment by reazulhoque** [comment]
@akharche We are forwarding the debug flag further down the line. We have to add the logic to enable the same affect as `NUMBA_DPPY_DEBUG` when we see this flag. Look [here](https://github.com/IntelPython/numba-dppy/blob/403cec4a16b158d323127f24080d931408d12cc5/numba_dppy/decorators.py#L72).

**Comment by akharche** [comment]
@reazulhoque Seems like it was fixed in https://github.com/IntelPython/numba-dppy/pull/424

**Comment by reazulhoque** [comment]
Thank you for the update. Closing this ticket.
