### ISSUE TITLE
Numpy array ops implementation

### ISSUE THREAD

**Issue by reazulhoque** [IntelPython/numba-dppy#209]
Following are some of the functions that are mostly supported by Numba and makes sense to run on the GPU. Some of them can be implemented using dpnp > 4.0 and some would require our own implementation.

		○ argpartition: remove
		○ astype: supported by Numba
			§ Implemented without parfor so we need our own implementation
			§ https://github.com/IntelPython/numba/blob/patched/numba/np/arrayobj.py#L4069
		○ Conj: Should be supported when we provide support for complex number
		○ Conjugate: Same as conj
		○ Cumprod: is alias of numpy.cumprod should be supported with later version of dpnp
		○ Cumsum: is alias of numpy.cumsum, should be supported with later version of dpnp, dpnp 4.0 does not implement it.
		○ Nonzero: 
			§ Implemented without parfor and dpnp does not support it yet.
			§ https://github.com/IntelPython/numba/blob/patched/numba/np/arraymath.py#L3112
		○ Std:
			§ Implemented without parfor and dpnp does not support it yet.
			§ https://github.com/IntelPython/numba/blob/patched/numba/np/arraymath.py#L439
		○ Take: 
			§ Not implemented using parfor and is not supported by dpnp.
			§ https://github.com/IntelPython/numba/blob/patched/numba/np/arrayobj.py#L3800
		○ Var:
			§ Implemented without parfor and dpnp does not support it yet.
			§ https://github.com/IntelPython/numba/blob/patched/numba/np/arraymath.py#L420
		○ Copy:
			§ Not implemented through parfor and not supported by dpnp yet
			§ https://github.com/IntelPython/numba/blob/patched/numba/np/arrayobj.py#L3983
		○ Flatten:
			§ Not implemented through parfor and not supported by dpnp yet
			§ https://github.com/IntelPython/numba/blob/patched/numba/np/arrayobj.py#L1766
		○ Fill
			§ Not supported by Numba but supported by dpnp later version than 4.0
		○ Ravel: Same as flatten
		○ Sort: supported by both numba and dpnp
			§ Should be implemented using dpnp
			§ Dpnp source: https://github.com/IntelPython/dpnp/blob/0.4.0/dpnp/dpnp_iface_sorting.py#L52
		○ Round:
			§ Not supported by Numba but supported by dpnp > 4.0
			§ Should be supported the next release of dpnp happens

**Comment by 1e-to** [comment]
From Numba-dppy table:
- astype: supported by Numba; Implemented without parfor so we need our own implementation; https://github.com/IntelPython/numba/blob/patched/numba/np/arrayobj.py#L4069; supported by dpnp
- compress: No in numba, no in dpnp
- conj: Should be supported when we provide support for complex number
- conjugate: Same as conj
- dump: No in numba, no in dpnp
- dumps: No in numba, no in dpnp
- fill: Not supported by Numba but supported by dpnp later version than 4.0
- getfield: No in numba, no in dpnp
- item: Not supported by Numba but supported by dpnp later version than 4.0
- itemset: supported by Numba; Implemented without parfor so we need our own implementation; https://github.com/IntelPython/numba/blob/5a1b372956ce881ebaf98c4ddd65681ece90ba0e/numba/np/arrayobj.py#L536; no in dpnp
- newbyteorder: No in numba; not planned in dpnp
- round: No in Numba; supported by dpnp
- setfield: No in numba, no in dpnp
- setflags: No in numba, no in dpnp
- sort: supported by both numba and dpnp; Should be implemented using dpnp; Dpnp source: https://github.com/IntelPython/dpnp/blob/0.4.0/dpnp/dpnp_iface_sorting.py#L52
- trace: No in numba, no in dpnp
- view:  supported by Numba; Implemented without parfor so we need our own implementation; https://github.com/IntelPython/numba/blob/5a1b372956ce881ebaf98c4ddd65681ece90ba0e/numba/np/arrayobj.py#L1996; no in dpnp

From dpnp table:
- argpartition
- choose
- clip
- compress
- copy
- cumprod
- cumsum
- diagonal
- dump
- dumps
- flatten
- getfield
- itemset
- nonzero
- partition
- prod
- put
- ravel
- resize
- searchsorted
- setfield
- setflags
- squeeze
- std
- take
- trace
- var
- view
