### ISSUE TITLE
Running tests fails

### ISSUE THREAD

**Issue by reazulhoque** [IntelPython/numba-dppy#22]
The following command results in error:

```
 python -m numba.runtests numba_dppy.tests
```

Error:
```
ValueError: Empty module name
```

**Comment by PokhodenkoSA** [comment]
It is strange. For SDC it works and for `numba.dppl` it worked. Possibly, there are some issues related to `numba.runtests` wich we should fit to.
Use `python -m unittest numba_dppy.tests`. I have fixed README in #24.
