### ISSUE TITLE
Generating native atomic instructions in Numba

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/numba-dppy#236]
DPC++ added a new feature to enable a SPIR-V extension to support FP32 and FP64 atomic adds. https://github.com/intel/llvm/pull/2765

We need to evaluate the changes and make sure we are generating similar code in Numba.

**Comment by reazulhoque** [comment]
An opt-in support was added. Details in this [PR](https://github.com/IntelPython/numba-dppy/pull/346).
