### ISSUE TITLE
Add GDB* support to Numba generated GPU kernels.

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/numba-dppy#26]
Currently, Numba-DPPY has not debugger support for GPU kernels. This feature request tracks the tasks that should be completed to enable debugger support in Numba-DPPY.

- [x] Evaluate what DWARF/debug symbols dpcpp generates for kernels.
- [x] Add flags to Numba-DPPY compilation to generate the same debug symbols for kernels as DPCPP when user has specified "debug=True".
- [x] Work with application debugger team (Matti Puputti) to identify steps on how to run Numba with GDB*
- [x] Develop examples to demonstrate how the debugger should be used.

**Comment by akharche** [comment]
Extended by https://github.com/IntelPython/numba-dppy/issues/149

**Comment by PokhodenkoSA** [comment]
@diptorupd What examples did you mean in checkbox "Develop examples to demonstrate how the debugger should be used"?
