### ISSUE TITLE
Changes to the dispacther to support dispacthing based on dpctl device_context

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/numba-dppy#271]
Numba-dppy includes changes to Numba (https://github.com/IntelPython/numba/pull/96) to support dispatching of functions based on `dpctl.device_context`. 

After discussions with Numba upstream developers, they have proposed adding a new way inside Numba to support our changes: https://github.com/numba/numba/pull/6770. Quoting Siu Kwan Lam:

> This patch will allow one to insert code to switch the options for `@jit`. I'm also considering an alternative at https://github.com/numba/numba/pull/6770#issuecomment-786887089, which is more flexible by allowing a function to be injected to transform the original dispatcher to something else.

- [x] Evaluate Siu's PR and build it locally on our systems
- [x] Provide review to Siu
- [x] Adapt the changes in https://github.com/IntelPython/numba/pull/96 to use the new design.
- [ ] Finalize changes and merge into numba-dppy (#278)

**Comment by PokhodenkoSA** [comment]
Pushed branches to IntelPython/numba:
Solution:
- https://github.com/IntelPython/numba/tree/wip/dispstack - branch from Siu
- https://github.com/IntelPython/numba/tree/wip/dispstack-patched - with all our patches applied except for https://github.com/IntelPython/numba/commit/6c70fc9a569d5ef30bf0ace4b0468556b479bdf2

Alternative solution:
- https://github.com/IntelPython/numba/tree/wip/dispstack_alt1 - branch from Siu
- https://github.com/IntelPython/numba/tree/wip/dispstack_alt1-patched - with all our patches applied except for https://github.com/IntelPython/numba/commit/6c70fc9a569d5ef30bf0ace4b0468556b479bdf2

**Comment by reazulhoque** [comment]
The device context was enabled in this PR: #493
