### ISSUE TITLE
Dead code

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dppy#276]
- https://github.com/IntelPython/numba-dppy/blob/main/numba_dppy/dispatcher.py - errors in code:
  - https://github.com/IntelPython/numba-dppy/blob/9c8dabf929368db96c3a2abf42072178b6cd9634/numba_dppy/dispatcher.py#L28
  - https://github.com/IntelPython/numba-dppy/blob/9c8dabf929368db96c3a2abf42072178b6cd9634/numba_dppy/dispatcher.py#L164
  - It seems that whole dispatcher.py file is not used.

**Comment by diptorupd** [comment]
@reazulhoque ping!

**Comment by PokhodenkoSA** [comment]
I have removed `dispatcher.py` few weeks ago.
