### ISSUE TITLE
DPPYFunction and DPPYFunctionTemplate classes in compiler.py

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/numba-dppy#288]
numba_dppy's `compiler.py` has left over code from the initial port from NUMBA-SPIRV.

@reazulhoque @PokhodenkoSA 
I do not think these functions and classes are being used anywhere:
- `compiler.py::compile_dppy_func`
- `compiler.py::compile_dppy_func_template`
- `compiler.py::DPPYFunctionTemplate`
- `compiler.py::DPPYFunction`
- `target.py::mark_ocl_device`

They were copied over from the ROCm backend. Do we still use or support them anywhere? If I recall correctly, these functions were used to generate functions with `spir_func` calling convention, *i.e.* device functions that are only callable from other kernels.

@reazulhoque what is the calling convention for `dppy_func`?

Also, what does the `numba.cuda` backend have any such equivalent functionality?

**Comment by reazulhoque** [comment]
@diptorupd These functions are used for supporting `@dppy.func`.

The calling convention for `dppy_func` is `spir_func`. 

`numba.cuda` backend provides same functionality using the `cuda.jit(device=True)` decorator option.

**Comment by diptorupd** [comment]
closing as it is working as designed and is not an issue.
