### ISSUE TITLE
All Numba-dppy tests and examples using the @njit decorator should be used with "with_context"

### ISSUE THREAD

**Issue by reazulhoque** [IntelPython/numba-dppy#30]
We need to update all the tests and examples that use:

```
@njit(parallel={'offload':True})
```

Following the example: https://github.com/IntelPython/numba-dppy/blob/main/numba_dppy/examples/dppl_with_context.py#L21

List of files that needs to update:

- numba/dppl/examples/pa_examples/test1-3d.py
- numba/dppl/examples/pa_examples/test1.py
- numba/dppl/examples/pa_examples/test1-5d.py
- numba/dppl/examples/pa_examples/test1-4d.py
- numba/dppl/examples/pa_examples/test1-2d.py
- numba/dppl/tests/dppl/test_prange.py
- numba/dppl/tests/dppl/test_numpy_comparison_functions.py
- numba/dppl/tests/dppl/test_dpnp_functions.py
- numba/dppl/tests/dppl/test_numpy_bit_twiddling_functions.py
- numba/dppl/tests/dppl/test_numpy_trigonomteric_functions.py
- numba/dppl/tests/dppl/test_numpy_floating_functions.py
- numba/dppl/tests/dppl/test_dppl_fallback.py
- numba/dppl/tests/dppl/test_parfor_lower_message.py
- numba/dppl/tests/dppl/test_vectorize.py
- numba/dppl/tests/dppl/test_numpy_math_functions.py

@diptorupd @PokhodenkoSA

**Comment by PokhodenkoSA** [comment]
It will allow to remove `offload` from IntelPython/numba here https://github.com/IntelPython/numba/pull/105.
