### ISSUE TITLE
Add flake8 in CI

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dppy#311]
flake8 in will find issues with imports.

_Originally posted by @PokhodenkoSA in https://github.com/IntelPython/numba-dppy/pull/297#discussion_r608501920_

**Comment by diptorupd** [comment]
@PokhodenkoSA I am using pylance with VS Code and it is catching tons of issues with unused args, unused variables etc. Will flake8 catch those as well?

**Comment by diptorupd** [comment]
I will open PRs for fixes for what I am seeing using pylance.

**Comment by PokhodenkoSA** [comment]
Unfortunately in my experience one time fix makes short-term effect. Implement CI checkers fixes the problem permanently.

**Comment by PokhodenkoSA** [comment]
> Will flake8 catch those as well?

Yes. It fixes some but also pylint and other tools follow.

**Comment by PokhodenkoSA** [comment]
Closed by https://github.com/IntelPython/numba-dppy/pull/544
