### ISSUE TITLE
Debugger: DWARF tag is not generated for local kernel variables

### ISSUE THREAD

**Issue by akharche** [IntelPython/numba-dppy#320]
DWARF tag (DILocalVariable) is not generated for local kernel variables. LLVM IR does not contain this tag for local variables.

Example: `!DILocalVariable(name: "b", scope: !12, file: !1, line: 23, type: !15)`

Fixed by https://github.com/IntelPython/numba/pull/217

**Comment by akharche** [comment]
```
@njit (debug=True)
def foo (arg):
    l1 = arg + 6        
    l2 = arg * 5.43      
    l3 = (arg, l1, l2, "bar")  
    print(arg, l1, l2, l3)   
```

gdb output for Numba-jit function:
![image](https://user-images.githubusercontent.com/41467010/115873106-3abe8900-a44b-11eb-8cd9-c9911b76a852.png)

**Comment by akharche** [comment]
Numba "info locals" returns local values in not readable view. It's impossible to understand the value of arguments

![image](https://user-images.githubusercontent.com/41467010/115874310-9ccbbe00-a44c-11eb-9e33-b0d0bbc414c2.png)

**Comment by PokhodenkoSA** [comment]
Fixed.
