### ISSUE TITLE
DEBUG: Support core dumping

### ISSUE THREAD

**Issue by akharche** [IntelPython/numba-dppy#324]
Check how core dumping support works with Numba-DPPy

**Comment by PokhodenkoSA** [comment]
Matti said that he tested support for core dump. He used special build of GDB which is not in main branch yet. From numba-dppy side there is no requirements as generated DWARF is good for the feature to work.
This issue will be closed. Reopen if needed or when GDB will be released with this feature and regression tests will be required on numba-dppy side.
