### ISSUE TITLE
Overwriting function arguments and local variables while gdb debugging

### ISSUE THREAD

**Issue by akharche** [IntelPython/numba-dppy#325]
User must be able to step the code line by line, and also read and write the function arguments and local variables

Blocked by: #36

**Comment by akharche** [comment]
Documentation for the functionality:
https://github.com/IntelPython/numba-dppy/pull/450
https://github.com/IntelPython/numba-dppy/pull/452

**Comment by PokhodenkoSA** [comment]
@akharche
I can not find example for overwriting local variables. Could you please provide a link?

**Comment by PokhodenkoSA** [comment]
It works. See `test_assignment_to_variable`.
