### ISSUE TITLE
Migrate Numba_dppy to dpctl 0.4.0

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/numba-dppy#33]
The memory manager module of `dpctl` was refactored and there are changes to API and paths of the functions. `Numba_dppy` should be updated to uses the latest API of `dpctl.`

@akharche please discuss with @reazulhoque and start with this task.

**Comment by PokhodenkoSA** [comment]
I have started to see problems:
1. `dpctl._memory` is now `dpctl.memory`
