### ISSUE TITLE
DEBUG: info functions

### ISSUE THREAD

**Issue by akharche** [IntelPython/numba-dppy#330]
Provide support for gdb `info functions` command

**Comment by vlad-perevezentsev** [comment]
Investigating **info func** command on `CPU` in `jit` code.

## info functions command
Dislays the list of functions in the debugged program

### Syntax

```
info functions
info functions [Regex]
```
### Parameters
`Regex`

If specified, the info functions command will list the functions matching the regex.
If omitted, the command will list all functions in all loaded modules (main program and shared libraries).

### Remarks
Note that running the info functions command without arguments can produce a lot of output as the list of all functions in all loaded shared libraries is typically very long.

### Examples
`njit-basic.py`
```
from numba import njit
@njit (debug=True)
def foo (arg):
    l1 = arg + 6        	# numba-kernel-breakpoint
    l2 = arg * 5.43             # second-line
    l3 = (arg, l1, l2, "bar")   # third-line
    print (arg, l1, l2, l3)     # fourth-line

def main():
    result = foo(5)
    result1 = foo(5.3)

if __name__ == '__main__':
    main()
```
`Commands used `

> source ${ONEAPI_ROOT}/debugger/latest/env/vars.sh
> NUMBA_OPT=0 gdb-oneapi -q python
> break njit-basic.py:45         #Set breakpoint in jit code
> run njit-basic.py

```
Breakpoint 1, __main__::foo$241 () at njit-basic.py:45
45          print (arg, l1, l2, l3)     # fourth-line
(gdb) info func foo
All functions matching regular expression "foo":

File njit-basic.py:
40:     void __main__::foo$241(long long);

Non-debugging symbols:
0x00007ffff634f190  lzma_stream_footer_encode@plt
0x00007ffff634f3c0  lzma_stream_footer_decode@plt
0x00007ffff6358190  lzma_stream_footer_encode
0x00007ffff635dd00  lzma_stream_footer_decode
0x00007fffefd4dd90  mkl_sparse_d_void_foo@plt
0x00007fffefd4f4f0  mkl_sparse_s_void_foo@plt
```
After `run njit-basic.py` command, we get to the jit function compiled for the `result` variable. 
We have only one compiled jit function at this stage, so `info func foo` will show one void function. 

Use `с` to jump to the breakpoint of the jit function for the `result1` variable.
```
(gdb) c
Continuing.
5 11 27.15 (5, 11, 27.15, 'bar')

Breakpoint 1, __main__::foo$242 () at njit-basic.py:45
45          print (arg, l1, l2, l3)     # fourth-line
(gdb) info func foo
All functions matching regular expression "foo":

File njit-basic.py:
40:     void __main__::foo$241(long long);
40:     void __main__::foo$242(double);

Non-debugging symbols:
0x00007ffff634f190  lzma_stream_footer_encode@plt
0x00007ffff634f3c0  lzma_stream_footer_decode@plt
0x00007ffff6358190  lzma_stream_footer_encode
0x00007ffff635dd00  lzma_stream_footer_decode
0x00007fffefd4dd90  mkl_sparse_d_void_foo@plt
```
We have two compiled jit functions at this stage, so "info func foo" will show two void functions.

#### Remarks
Use a more correct Regex to remove the `Non-debugging symbols` output, e.g. `^__.*foo`
```
(gdb) info func ^__.*foo
All functions matching regular expression "^__.*foo":

File njit-basic.py:
40:     void __main__::foo$241(long long);
40:     void __main__::foo$242(double);
```

**Comment by PokhodenkoSA** [comment]
Good test for documentation. I will take it to docs about debugging.

**Comment by PokhodenkoSA** [comment]
Need to be checked on GPU

**Comment by PokhodenkoSA** [comment]
Implemented. See docs https://intelpython.github.io/numba-dppy/latest/user_guides/debugging/info.html#info-functions.
