### ISSUE TITLE
DEBUG: Step inside function calls (command “step”)

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dppy#352]
We can not debug nested functions.
Check where debug info missed. 
Investigate how to receive debug info on each step of pipeline.

Collected info about steps will help to write docs about compilation pipeline #385.

- [x] implement and test #424 
- [x] update docs

**Comment by PokhodenkoSA** [comment]
Search for nested function info in debug info
- NUMBA_DUMP_OPTIMIZED - print, after lowering and optimizations
  - Contains nested function information

**Comment by 1e-to** [comment]
Spirv investigation: https://github.com/IntelPython/numba-dppy/issues/418

**Comment by PokhodenkoSA** [comment]
Implemented by https://github.com/IntelPython/numba-dppy/pull/424
