### ISSUE TITLE
Removing kernel wrapper function

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dppy#364]
Couple of questions @reazulhoque @DrTodd13 @PokhodenkoSA:

1. Do we need the `meminfo` and `parent` attributes? We are not using it in any place?
2. Will it be possible to add an address space specifier to the two attributes based on our `GenericPointerModel`?

It will be useful for my work on removing the kernel wrapper function. I made the needed changes so that address space casting of kernel arguments is done during the `decode_arguments` phase at the time of lowering. However, the next step of unflattening the array arguments into a struct fails because the data model does not match.

_Originally posted by @diptorupd in https://github.com/IntelPython/numba-dppy/pull/287#r617173505_

**Comment by PokhodenkoSA** [comment]
@diptorupd 
I have merged #287. Additional changes could be made in another PR.
What is required for removing wrapper? As I understand removing meminfo and paret is necessary for removing wrapper. Is it correct? What could be our next steps here?

**Comment by diptorupd** [comment]
@PokhodenkoSA 

There are two options: 
1. remove meminfo and parent as you suggest. 
2. convert these two attributes to CPointer.

Let me discuss with @reazulhoque tomorrow and propose a patch.
