### ISSUE TITLE
All njit tests should assert offload

### ISSUE THREAD

**Issue by reazulhoque** [IntelPython/numba-dppy#366]
All the `@njit` tests currently do not check if `parfor` regions were offloaded to SYCL device or not. This would show tests as passed even when it is failing to offload. Checks should be added. One possible check is implemented [here](https://github.com/IntelPython/numba-dppy/pull/303/files#diff-c170cf8bfbfb27c0a480be19af90787100517ee4c795b9d44b3ee2c24df61c59R83).

**Comment by PokhodenkoSA** [comment]
@reazulhoque could you take it?

**Comment by diptorupd** [comment]
Done in #466
