### ISSUE TITLE
Second off-loaded function not in DWARF

### ISSUE THREAD

**Issue by mpuputti** [IntelPython/numba-dppy#37]
Using a build with the commit [#27](https://github.com/IntelPython/numba-dppy/pull/27).

The attached script sum_2.py has a kernel function 'data_parallel_sum', which calls another off-loaded function 'kernel_sum'.
GDB can set breakpoints in the function 'data_parallel_sum', but not in the function 'kernel_sum'.

To reproduce:

> $ export NUMBA_DPPL_DEBUG=1
> $ export NUMBA_SAVE_DPPL_IR_FILES=1
> $ gdb-oneapi -q --args python sum_2.py
> (gdb) break sum_2.py:13
> (gdb) run
> <GDB hits a breakpoint at line 16>
> (gdb) backtrace

Expected results: GDB hits breakpoint at line 13. Command "backtrace" lists both functions "kernel_sum" and "data_parallel_sum".
Detected : GDB hits a breakpoint at line 16, which is not in the function "kernel_sum", but in the function "data_parallel_sum".
Further more, it is not possible to enter the function "data_parallel_sum" even by stepping.

Investigating the LLVM IR, we can see that the "data_parallel_sum" is not introduced in the debug data (at the end of the file llvm_kernel.ll).
Since it is not in the IR, it is also not in the IGC generated DWARF.

Attached:
- [sum_2.zip](https://github.com/IntelPython/numba-dppy/files/5623487/sum_2.zip)
- [llvm_kernel.zip](https://github.com/IntelPython/numba-dppy/files/5623488/llvm_kernel.zip)

**Comment by akharche** [comment]
Fixed by: https://github.com/IntelPython/numba-dppy/pull/424
