### ISSUE TITLE
Numba-dppy performance regression in dppy.kernel versions

### ISSUE THREAD

**Issue by adarshyoga** [IntelPython/numba-dppy#407]
Reporting a performance regression with Numba-dppy (0.14.1+10.gcae3063) + dpctl (0.8.0rc2+2.g4fbf7a9) + numba (0.53.1+8.gddf817af0). 
The regression is seen in dppy.kernel versions of blackscholes and pairwise distance workloads. 
Blackscholes kernel used to execute in 0.07 seconds. In this latest release it executes in 29.69 secs, have a performance regression of 424X.

To reproduce the error run the kernel version of [blackshcoles benchmark](https://github.com/IntelPython/dpbench/tree/main/native/blackscholes/GPU) in dpbench.

> cd <PATH_TO_DPBENCH>
> python automate_run.py -ws blackscholes -i numba -p gpu -a test -k

**Comment by reazulhoque** [comment]
This https://github.com/IntelPython/numba-dppy/pull/408#pullrequestreview-669449460 should fix it.
