### ISSUE TITLE
Get dwarf from Numba assembly

### ISSUE THREAD

**Issue by 1e-to** [IntelPython/numba-dppy#440]
This works for cpu (@njit),  
For kernels, you need to use a different method, in this information does not get into the dwarf 

We need to set numba environment variable and run script and get info 
```python
NUMBA_DUMP_ASSEMBLY=1 python njit-basic.py > njit-basic-asm.txt 
```

Clear file from prints and unrecognized characters (-, =, !, \) 

Get compiled from asm 
```python
as -o o njit-basic-asm.txt 
```

Get dwarf with objdump 
```python
objdump -W o > o_dwarf 
```

**Comment by PokhodenkoSA** [comment]
@1e-to 
Is it in documentation already?

**Comment by vlad-perevezentsev** [comment]
@PokhodenkoSA yes. It is in documentation. [PR 458](https://github.com/IntelPython/numba-dppy/pull/458) added it.
[Docs link](https://intelpython.github.io/numba-dppy/latest/developer_guides/tools.html#getting-the-dwarf-from-numba-assembly-for-njit)
