### ISSUE TITLE
All tests in numba_dppy/tests/dppl should be updated

### ISSUE THREAD

**Issue by reazulhoque** [IntelPython/numba-dppy#47]
1. `DPPLTestCase` should be replaced with `unittest.TestCase`.
2. `from numba_dppy.testing import DPPLTestCase` should be removed
3. `from numba_dppy.testing import unittest` should be replaced by `import unittest`
4. All `from __future__ ` lines should be removed
5. `numba_dppy/testing.py` should be checked if it is needed anymore.

**Comment by PokhodenkoSA** [comment]
`numba_dppy/testing.py` contains used functions (i.e. `expectedFailureIf()` decorator). So each element of this module could be considered - is used or not.

**Comment by reazulhoque** [comment]
@vlad-perevezentsev any update on this?
