### ISSUE TITLE
GDB error occurs when setting a breakpoint

### ISSUE THREAD

**Issue by 1e-to** [IntelPython/numba-dppy#473]
Sometimes an error occurs when setting a breakpoint. Random and does not depend on anything. About once every five runs
Tested with numba 0.53, numba-dppy 0.15 and NEO  21.20.19883 on GPU

(numba-dppy-new) etotmeni@ansatnuc05:/localdisk/work/etotmeni/numba-dppy$ gdb-oneapi --args python /localdisk/work/etotmeni/numba-dppy/numba_dppy/examples/debug/simple_dppy_func.py
GNU gdb (Intel(R) Distribution for GDB* 2021.1.2) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.; (C) 2020 Intel Corp.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.

For information about how to find Technical Support, Product Updates,
User Forums, FAQs, tips and tricks, and other support information, please visit:
<http://www.intel.com/software/products/support/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...
(gdb) b simple_dppy_func.py:28
No source file named simple_dppy_func.py.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (simple_dppy_func.py:28) pending.
(gdb) r
Starting program: /localdisk/work/etotmeni/miniconda3/envs/numba-dppy-new/bin/python /localdisk/work/etotmeni/numba-dppy/numba_dppy/examples/debug/simple_dppy_func.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 2660854]
[Detaching after fork from child process 2660855]
[Detaching after fork from child process 2660862]
[New Thread 0x7fffd6e5f700 (LWP 2660864)]
intelgt: gdbserver-gt started for process 2660844.
intelgt: attached to device 1 of 1; id 0x9bca (Gen9)
[New Thread 0x7fffc6027700 (LWP 2660876)]
[Detaching after fork from child process 2660877]
[Detaching after fork from child process 2660878]
[Detaching after fork from child process 2660879]
[Detaching after fork from child process 2660880]
[Detaching after fork from child process 2660881]
[New Thread 0x7fffb6792700 (LWP 2660888)]
[New Thread 0x7fffb6391700 (LWP 2660889)]
[New Thread 0x7fffb5f90700 (LWP 2660890)]
[New Thread 0x7fffb5b8f700 (LWP 2660891)]
[New Thread 0x7fffb538d700 (LWP 2660893)]
[New Thread 0x7fffb578e700 (LWP 2660892)]
[New Thread 0x7fffb4f8c700 (LWP 2660894)]
[New Thread 0x7fff97fff700 (LWP 2660897)]
[New Thread 0x7fffb478a700 (LWP 2660896)]
[New Thread 0x7fffb4b8b700 (LWP 2660895)]
[New Thread 0x7fff9ffff700 (LWP 2660898)]
[Detaching after fork from child process 2660905]
[Detaching after fork from child process 2660906]
[New Thread 1.1073741824]
[New Thread 1.1073742080]

Thread 2.2 received signal SIGTRAP, Trace/breakpoint trap.
[Switching to Thread 1.1073741824 lane 0]
0x0000000000000000 in _____EMPTY_CODE ()
(gdb) 

(gdb) bt
#0  0x0000000000000000 in _____EMPTY_CODE ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Comment by 1e-to** [comment]
Source code:

import numpy as np
import numba_dppy as dppy
import dpctl


@dppy.func(debug=True)
def func_sum(a_in_func, b_in_func):
    result = a_in_func + b_in_func
    return result


@dppy.kernel(debug=True)
def kernel_sum(a_in_kernel, b_in_kernel, c_in_kernel):
    i = dppy.get_global_id(0)
    c_in_kernel[i] = func_sum(a_in_kernel[i], b_in_kernel[i])


global_size = 10
a = np.arange(global_size, dtype=np.float32)
b = np.arange(global_size, dtype=np.float32)
c = np.empty_like(a)

with dpctl.device_context("opencl:gpu") as gpu_queue:
    kernel_sum[global_size, dppy.DEFAULT_LOCAL_SIZE](a, b, c)

print("Done...")

**Comment by vlad-perevezentsev** [comment]
This bug was fixed in the new oneAPI 2021.4
