### ISSUE TITLE
Using native atomics does not improve performance of atomic add

### ISSUE THREAD

**Issue by adarshyoga** [IntelPython/numba-dppy#487]
I tried out the pair counting code, which uses atomic add to compute histogram. Using native atomics does not produce any change in execution time.

DEFAULT ATOMICS:
```
$  python run_gpairs.py --steps 1
Time: 8.13 secs
```
NATIVE ATOMICS:
```
$ NUMBA_DPPY_ACTIVATE_ATOMCIS_FP_NATIVE=1 NUMBA_DPPY_LLVM_SPIRV_ROOT=<PATH_TO_DPCPP_LLVM_SPIRV>  python run_gpairs.py --steps 1
Time: 8.54 secs
```

**Comment by reazulhoque** [comment]
@adarshyoga is there a native dpcpp version of this workload?

**Comment by reazulhoque** [comment]
We have ensured for hardware supported datatypes and correctly written kernels in Numba-dppy we do get expected performance improvements using native atomic instructions.
