### ISSUE TITLE
CI passing with missing runtime dependency in conda recipe

### ISSUE THREAD

**Issue by reazulhoque** [IntelPython/numba-dppy#499]
Numba-dppy uses `packaging` package [here](https://github.com/IntelPython/numba-dppy/blob/main/numba_dppy/config.py#L17). `packaging` is not provided as a runtime dependency in conda-recipe. CI did not complain about it for the last two months. Users trying to use Numba-dppy packaged with ONEAPI base toolkit will encounter error `ModuleNotFoundError: No module named 'packaging' `.

**Comment by PokhodenkoSA** [comment]
Modile [packaging](https://pypi.org/project/packaging/) is a dependency of pytest. That is why it is present in most of our environments.
I will fix it.

**Comment by PokhodenkoSA** [comment]
We definitely need a system to check dependencies.
