### ISSUE TITLE
Extend local variables lifetime for improving debugging 

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dppy#527]
Numba minimizes variables lifetime even with NUMBA_OPT=0.
You can see variable values between its first use and the last use.
We need to introduce possibility to extend variables lifetime for the scope where variable is visible in Python code.

Related #525.

https://github.com/numba/numba/pull/6623

**Comment by PokhodenkoSA** [comment]
https://github.com/numba/numba/pull/7421 fixes it.

**Comment by vlad-perevezentsev** [comment]
7421 fixed this issue.
I added support for `NUMBA_EXTEND_VARIABLE_LIFETIMES` env variable to GDB tests.
[PR 600](https://github.com/IntelPython/numba-dppy/pull/600)
