### ISSUE TITLE
Numba-dppy tests issues with commit `3bbc215cc4c40637b1db5ed3f21fd07d640cb858`

### ISSUE THREAD

**Issue by reazulhoque** [IntelPython/numba-dppy#54]
Getting the following error when executing the following command:

`python -m unittest numba_dppy.tests`

**Error**:
```
numba/core/utils.py", line 327, in __setitem__
    raise AssertionError("key already in dictionary: %r" % (key,))
AssertionError: key already in dictionary: 'dppy'
```

dpctl version: 0.5.0rc1
numba branch: patched (0bf83efd8703948d1ab4fc8161548ffeb2e3ba28)

**Comment by PokhodenkoSA** [comment]
It usually relate to uncleaned `dppl` code in Numba. I will check.

**Comment by PokhodenkoSA** [comment]
@reazulhoque please, check with dpctl 0.5.0rc2.

**Comment by reazulhoque** [comment]
Issue resolved.
