### ISSUE TITLE
Update how we load dpctl library

### ISSUE THREAD

**Issue by reazulhoque** [IntelPython/numba-dppy#56]
In [this](https://github.com/IntelPython/numba-dppy/blob/main/numba_dppy/initialize.py#L25) line we use the `find_library()` function provided by `ctypes.util` module to find the dpctl library.

Here is the documentation of `find_library()` (https://docs.python.org/3/library/ctypes.html) and it seems like it returns the full path to the library we intend to load.

In our case we  already have to full path to the library and hence can simply pass that. Possible patch below:

```
diff --git a/numba_dppy/initialize.py b/numba_dppy/initialize.py
index c8ba562..40a9bf1 100644
--- a/numba_dppy/initialize.py
+++ b/numba_dppy/initialize.py
@@ -22,7 +22,7 @@ def initialize_all():
         paths = glob.glob(os.path.join(os.path.dirname(dpctl.__file__), '*DPPLSyclInterface*'))

     if len(paths) == 1:
-        ll.load_library_permanently(find_library(paths[0]))
+        ll.load_library_permanently(paths[0])
     else:
         raise ImportError
                              
```

**Comment by PokhodenkoSA** [comment]
Import is not necessary too now:
https://github.com/IntelPython/numba-dppy/blob/ff8fe55f50c14b0e010f32d570d974f572cdd956/numba_dppy/initialize.py#L4

**Comment by vlad-perevezentsev** [comment]
@PokhodenkoSA We need to import find_library for load the OpenCL library.
29 ll.load_library_permanently(find_library('OpenCL'))

**Comment by PokhodenkoSA** [comment]
> We need to import find_library

@reazulhoque proposed to remove its using in his description.

**Comment by PokhodenkoSA** [comment]
> Import is not necessary too now:

I was wrong. It is needed.

**Comment by reazulhoque** [comment]
We only need to do it for DPCTLSyclInterface library. @vlad-perevezentsev  can you please check after we remove the find_library if my hypothesis is correct?
