### ISSUE TITLE
ModuleNotFoundError after installing numba-dppy from source

### ISSUE THREAD

**Issue by adarshyoga** [IntelPython/numba-dppy#567]
Doing an "import numba_dppy" after installing numba-dppy from source gives the following error.

```
ModuleNotFoundError: No module named 'numba_dppy.target_dispatcher'
```

**Comment by PokhodenkoSA** [comment]
`target_dispatcher.py` is very old module removed on numba-dppy 0.15.0. It could be used by our numba 0.53.1. It is not reuired by numba 0.54.0. Could you please provide versions of your packages?

**Comment by adarshyoga** [comment]
@PokhodenkoSA, I am using oneapi 2021.3. The version of numba that is installed when I do a conda installl of numba is 0.53.1. After this, when I run setup.py develop it seems to replace numba with 0.54.0. The version of numba-dppy is 0.15.0.

**Comment by PokhodenkoSA** [comment]
@adarshyoga 
I have provided packages from oneAPI 2021.4. Did it solve the problem? Can I close the ticket?

**Comment by PokhodenkoSA** [comment]
Reopen if needed.
