### ISSUE TITLE
Fix public CI w/ Numba 0.55

### ISSUE THREAD

**Issue by 1e-to** [IntelPython/numba-dppy#592]
Run on Linux:

============================= test session starts ==============================
platform linux -- Python 3.8.12, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/runner/work/numba-dppy/numba-dppy
collected 0 items / 1 error

==================================== ERRORS ====================================
________________________ ERROR collecting test session _________________________
/usr/share/miniconda/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:961: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:961: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:843: in exec_module
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
/usr/share/miniconda/lib/python3.8/site-packages/numba_dppy/__init__.py:520: in <module>
    from numba_dppy.retarget import offload_to_sycl_device
/usr/share/miniconda/lib/python3.8/site-packages/numba_dppy/retarget.py:19: in <module>
    from numba.core.dispatcher import TargetConfig
E   ImportError: cannot import name 'TargetConfig' from 'numba.core.dispatcher' (/usr/share/miniconda/lib/python3.8/site-packages/numba/core/dispatcher.py)
=========================== short test summary info ============================
ERROR  - ImportError: cannot import name 'TargetConfig' from 'numba.core.disp...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.58s ===============================
Error: Process completed with exit code 2.

**Comment by PokhodenkoSA** [comment]
Fixed by pinning in https://github.com/IntelPython/numba-dppy/issues/592.
Support for the latest version is in https://github.com/IntelPython/numba-dppy/pull/585.
