### ISSUE TITLE
Dpctl context manager should be able to trigger Numba_dppy pipeline

### ISSUE THREAD

**Issue by reazulhoque** [IntelPython/numba-dppy#618]
Users should be able to offload `@numba.njit` using Numba-dppy's pipeline. The following code snippet will not offload the `njit` decorated function to SYCL device using dpctl's context_manager.

```
@njit
def f1(a, b):
    c = a + b
    return c

a = np.ones(N, dtype=np.float32)
b = np.ones(N, dtype=np.float32)

device = dpctl.select_default_device()

with dpctl.device_context(device):
        c = f1(a, b)
```

**Comment by PokhodenkoSA** [comment]
Related discussion - https://github.com/IntelPython/numba-dppy/discussions/613

**Comment by reazulhoque** [comment]
Closing it as duplicate of #613.
