### ISSUE TITLE
Provide mechanism to disable CPU Fallback

### ISSUE THREAD

**Issue by adarshyoga** [IntelPython/numba-dppy#73]
Numba njit GPU function silently executes on the CPU whenever Numba is not able to successfully compile the function for the GPU. This can be sometimes frustrating to the user who has assumes the code works correctly on the GPU, while in fact it has been executing on the CPU. While providing feedback will help slightly, we really need to provide some mechanism using which the user can disable CPU fallback and force program failure when GPU compilation fails. One way would be through an environment variable.

**Comment by diptorupd** [comment]
@1e-to can we close this once your #40 is merged?

**Comment by PokhodenkoSA** [comment]
Implemented.
