### ISSUE TITLE
Compiled Sycl kernels should be cached based on the device type and should be reused

### ISSUE THREAD

**Issue by reazulhoque** [IntelPython/numba-dppy#82]
## Feature request

Sycl can have different queues for each device and for the same device. We should cache kernels/programs we have compiled based on the type of device and reuse them.

**Comment by diptorupd** [comment]
@reazulhoque Can you add comment on how this was implemented and close this ticket?

**Comment by diptorupd** [comment]
@reazulhoque any updates?

**Comment by diptorupd** [comment]
SYCL kernel caching is done based on SYCL context.
