### ISSUE TITLE
Support environment variable NUMBA_DUMP_ASSEMBLY

### ISSUE THREAD

**Issue by adarshyoga** [IntelPython/numba-dppy#84]
NUMBA_DUMP_ASSEMBLY environment variable outputs the assembly code of the generated kernel. Supporting this variable on the GPU will make it easier to identify performance issues in the kernel.

**Comment by diptorupd** [comment]
@PokhodenkoSA  we already have this feature exposed using `NUMBA_DPPY_SAVE_IR_FILES` to save the generate. We should add numba-dppy specific environment variables to README.

**Comment by diptorupd** [comment]
Generating the LLVM IR and SPIR-V bitcode for `numba-dppy` is possible using the `NUMBA_DPPY_SAVE_IR_FILES`. The files currently get saved to the `tmp` directory, but #481 will change that and allow saving the files to the current working directory.
