### ISSUE TITLE
Support automatically offloading of numpy.linalg functions on SYCL GPU devices

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/numba-dppy#89]
`numpy.linalg` functions are not directly implemented inside Numba and we cannot generate SPIRV for such functions. The detour will be utilize an optimized library implementation for SYCL GPU devices and call the library function from the LLVM module. The strategy is similar to how `numpy.linalg` functions are handled on the CPU by Numba.

**Comment by reazulhoque** [comment]
Some `numpy.linalg` functions are currently implemented using dpnp. List of supported functions with limited argument support are:

1. cholesky
2. det
3. dot
4. eig
5. eigvals
6. matmul
7. matrix_power
8. matrix_rank
9. multi_dot
